FROM python:3.10

WORKDIR /app

COPY worker/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY worker/ .

CMD ["celery", "-A", "worker", "worker", "--loglevel=info"]
